name: HelloWorldApp
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, x64]
    steps:  
      - name: checkout repo content
        uses: actions/checkout@v1
        
      - name: Testing Java 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11.0.4'
      - run: |
          java -version
          java HelloWorldApp.java

